//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFCustomHeaderDemo.Console.ComplexCustomHeaderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComplexCustomHeaderService.IComplexCustomHeaderService")]
    public interface IComplexCustomHeaderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplexCustomHeaderService/DoWork", ReplyAction="http://tempuri.org/IComplexCustomHeaderService/DoWorkResponse")]
        string DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComplexCustomHeaderService/DoWork", ReplyAction="http://tempuri.org/IComplexCustomHeaderService/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComplexCustomHeaderServiceChannel : WCFCustomHeaderDemo.Console.ComplexCustomHeaderService.IComplexCustomHeaderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComplexCustomHeaderServiceClient : System.ServiceModel.ClientBase<WCFCustomHeaderDemo.Console.ComplexCustomHeaderService.IComplexCustomHeaderService>, WCFCustomHeaderDemo.Console.ComplexCustomHeaderService.IComplexCustomHeaderService {
        
        public ComplexCustomHeaderServiceClient() {
        }
        
        public ComplexCustomHeaderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComplexCustomHeaderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComplexCustomHeaderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComplexCustomHeaderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
