//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFCustomHeaderDemo.Console.SimpleCustomHeaderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimpleCustomHeaderService.ISimpleCustomHeaderService")]
    public interface ISimpleCustomHeaderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCustomHeaderService/DoWork", ReplyAction="http://tempuri.org/ISimpleCustomHeaderService/DoWorkResponse")]
        string DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCustomHeaderService/DoWork", ReplyAction="http://tempuri.org/ISimpleCustomHeaderService/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleCustomHeaderServiceChannel : WCFCustomHeaderDemo.Console.SimpleCustomHeaderService.ISimpleCustomHeaderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleCustomHeaderServiceClient : System.ServiceModel.ClientBase<WCFCustomHeaderDemo.Console.SimpleCustomHeaderService.ISimpleCustomHeaderService>, WCFCustomHeaderDemo.Console.SimpleCustomHeaderService.ISimpleCustomHeaderService {
        
        public SimpleCustomHeaderServiceClient() {
        }
        
        public SimpleCustomHeaderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleCustomHeaderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleCustomHeaderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleCustomHeaderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
